export enum AtlasStatus {
  "SYNTAX_ERROR" = "SYNTAX_ERROR",
  "TYPE_ERROR" = "TYPE_ERROR",
  "SEMANTIC_ERROR" = "SEMANTIC_ERROR",
  "RUNTIME_ERROR" = "RUNTIME_ERROR",
  "SUCCESS" = "SUCCESS",
  "VALID" = "VALID",
}
