export const Errors = {
  UnterminatedString: "unterminated string",
  UnexpectedCharacter: "unexpected character",
  UndefinedVariable: "undefined variable",
  ExpectedAssignment: "expected assignment",
  ExpectedRightParen: "expected right parenthesis",
  ExpectedColon: "expected colon",
  ExpectedSemiColon: "expected semicolon",
  ExpectedExpression: "expected expression",
  ExpectedLeftOperand: "expected left-hand operand",
  ExpectedNumber: "expected number",
  ExpectedBoolean: "expected boolean",
  ExpectedIdentifier: "expected identifier",
  UnexpectedUnaryOperator: "unexpected unary operator",
  UnexpectedBinaryOperator: "unexpected binary operator",
  ProhibitedZeroDivision: "prohibited division by zero",
};
